services:
- type: web
  name: esp32-live-mjpeg
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app --workers 2 --threads 8 --bind 0.0.0.0:$PORT
  envVars:
    - key: UPLOAD_TOKEN
      value: changeme         # ← must match ESP32 sketch
    - key: FLAG_TOKEN
      value: changeme         # ← must match ESP32 + dashboard.js
